server:
  port: 8761          #default port of eureka 
  servlet:
    application-display-name: eureka-naming-server
    
eureka:
  client:
    register-with-eureka: false                  #(false)it means eureka should contain the list of other clients and eureka should not contain itself.
    fetch-registry: false